# Generated by Django 3.1 on 2020-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Director', models.CharField(max_length=30)),
                ('Cast_I', models.CharField(max_length=30)),
                ('Cast_II', models.CharField(max_length=30)),
                ('Name', models.TextField()),
                ('ReleaseYear', models.IntegerField()),
                ('ImdbRating', models.CharField(max_length=3)),
                ('Genre', models.TextField(null=True)),
                ('Language', models.CharField(max_length=20, null=True)),
                ('Like', models.IntegerField()),
                ('Dislike', models.IntegerField()),
                ('Availbility', models.TextField(null=True)),
            ],
        ),
    ]
