# Generated by Django 3.1 on 2020-08-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creator', models.CharField(max_length=30)),
                ('Content', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('MovieLinked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
            ],
        ),
    ]
