# Generated by Django 3.1 on 2020-08-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='MovieLinked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_review', to='movie.movies'),
        ),
    ]
