# Generated by Django 3.1 on 2020-08-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200805_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Creator',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Content',
            new_name='Review',
        ),
    ]
