# Generated by Django 3.1 on 2020-08-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200807_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='Availbility',
            new_name='avail',
        ),
    ]
